export const unreadMessagesCount = state => state.messages.main.length
export const unreadNotificationsCount = state => state.notifications.main.length
export const remainTasksCount = state => state.tasks.main.length
export const currentUser = state => state.user.main
export const totalProduct = state => state.products.main
export const brands = state => state.brands.main
export const brand = state => state.brands.brand
export const token = state => state.user.token
export const isAuthenticated = state => !!state.user.token
export const users = state => state.user.users
